### ISSUE TITLE
`.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by lionup** [astamm/nloptr#10]
Hi Jelmer, I've been trying to install nloptr on Ubuntu 14.04 with R3.1, but get the following error. Would you please help me? Thanks. 
- installing _source_ package ‘nloptr’ ...
  checking for g++... g++
  checking whether the C++ compiler works... yes
  checking for C++ compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking how to run the C++ preprocessor... g++ -E
  checking whether we are using the GNU C++ compiler... (cached) yes
  checking whether g++ accepts -g... (cached) yes
  checking for pkg-config... yes
  configure: Now testing for NLopt header file.
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking nlopt.h usability... yes
  checking nlopt.h presence... yes
  checking for nlopt.h... yes
  configure: Suitable NLopt library found.
  configure: creating ./config.status
  config.status: creating src/Makevars
  config.status: creating R/PkgFlags.R
  *\* libs
  g++ -I/usr/share/R/include -DNDEBUG      -fpic  -O3 -c dummy.cpp -o dummy.o
  gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG     -I/usr/local/include   -fpic  -O3 -c nloptr.c -o nloptr.o
  g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o nloptr.so dummy.o nloptr.o -L/usr/local/lib -lnlopt -lm -L/usr/lib/R/lib -lR
  /usr/bin/ld: /usr/local/lib/libnlopt.a(general.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
  /usr/local/lib/libnlopt.a: error adding symbols: Bad value
  collect2: error: ld returned 1 exit status
  make: **\* [nloptr.so] Error 1
  ERROR: compilation failed for package ‘nloptr’
- removing ‘/home/lionup/R/x86_64-pc-linux-gnu-library/3.1/nloptr’
  Error: Command failed (1)

**Comment by jyypma** [comment]
Hi Ran,

thank you for your message. It looks like configure detects that NLopt is
installed on your system, but then something goes wrong during linking.

How did you install NLopt?

If you do not need NLopt for other purposes thant to work with R, you could
remove the NLopt installation. If you then try to install nloptr again, the
configure script will automatically download and install NLopt and use the
same compiler/linker that R uses, so the versions will work together.

Many thanks and best wishes,
Jelmer

**Comment by FlorianSchwendinger** [comment]
Hi,

I had something which sounds like the same issue, the following did resolve it in my case
1. I installed nlopt into a local library (e.g. ~/lib/nlopt)
   
   ``` bash
       wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
       tar -xf nlopt-2.4.2.tar.gz 
       cd nlopt-2.4.2/
       ./configure --enable-shared --prefix=$HOME/lib/nlopt
       make
       make install
   ```
2. Afterwards I had to change the Makevars since when I was trying to install nloptr from source 
   (`R CMD INSTALL nloptr`) the configure file always found the previously installed library first.
   To avoid this I altered the Makevars in `nloptr/src/Makevars` (see below) and deleted the
   configure file (`nloptr/configure`).   
   
   I changed `nloptr/src/Makevars` from
   (NOTE: one has to run `R CMD INSTALL nloptr` once before deleting configure to get a Makevars file) 
   
   ``` bash
   ## ... comments
   PKG_CFLAGS= -I/usr/local/include 
   PKG_LIBS= -L/usr/local/lib -lnlopt -lm 
   ## comments ...
   ```
   
   to
   
   ``` bash
   ## ... comments
   PKG_CFLAGS= -I/home/florian/lib/nlopt/include 
   PKG_LIBS= -L/home/florian/lib/nlopt/lib -lnlopt -lm 
   ## comments ...
   ```
   
   and installed nloptr from source
   
   ``` bash
   R CMD INSTALL nloptr
   ```

<br>          

This is of course not the most sophisticated solution but it worked.

**Comment by lionup** [comment]
Dear @FlorianSchwendinger and @Jelmer,

Thanks a lot for your help. I will have a try and see how it goes.

Best regards,
Ran

**Comment by vishwakarmarhl** [comment]
I fell for the same issue. Even upon trying the steps by @FlorianSchwendinger it did not work.

I have already installed** nlopt-2.4.2 **in /usr/local/lib using
./configure --enable-shared
make 
sudo make install

Verified the /usr/local/lib to have the following objects upon installation. This is also added to LD_LIBRARY_PATH
ls /usr/local/lib/libn*
libnlopt.a         libnlopt.la        libnlopt.so        libnlopt.so.0      libnlopt.so.0.8.2

I have attempted to install twice. One is installation from source and other is from github using the devtools package.

**1.)  Here is the first error case when i attempt to install nloptr_1.0.4.tar.gz from source**
`
[dbadmin@vertica-team devtools]$ sudo /opt/vertica/R/bin/R CMD INSTALL nloptr/
* installing to library ‘/opt/vertica/R/library’
* installing *source* package ‘nloptr’ ...
file ‘src/Makevars.in’ has the wrong MD5 checksum
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for pkg-config... yes
configure: Now testing for NLopt header file.
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking nlopt.h usability... yes
checking nlopt.h presence... yes
checking for nlopt.h... yes
configure: Suitable NLopt library found.
configure: creating ./config.status
config.status: creating src/Makevars
** libs
make: Nothing to be done for `all'.
installing to /opt/vertica/R/library/nloptr/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/opt/vertica/R/library/nloptr/libs/nloptr.so':
  /opt/vertica/R/library/nloptr/libs/nloptr.so: undefined symbol: nlopt_set_maxtime
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/opt/vertica/R/library/nloptr’
`

**2.) In my case I am lucky to have an internet connection so that I can test out the installation from the git repo. Here is the log when I try to use install_github with the devtools library.**

`
> library('devtools')
> install_github("jyypma/nloptr")
Downloading GitHub repo jyypma/nloptr@master
from URL https://api.github.com/repos/jyypma/nloptr/zipball/master
Installing nloptr
'/opt/vertica/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL '/tmp/RtmpX15lex/devtools1ba36d5286a/jyypma-nloptr-dc6c3ba'  \
  --library='/opt/vertica/R/library' --install-tests

* installing *source* package ‘nloptr’ ...
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for pkg-config... yes
configure: Now testing for NLopt header file.
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking nlopt.h usability... yes
checking nlopt.h presence... yes
checking for nlopt.h... yes
configure: Now testing for NLopt versison number.
configure: Suitable NLopt library found.
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating R/PkgFlags.R
** libs
g++ -I/opt/vertica/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -D_FORTIFY_SOURCE=2 -g  -c dummy.cpp -o dummy.o
gcc -std=gnu99 -I/opt/vertica/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c nloptr.c -o nloptr.o
g++ -shared -L/opt/vertica/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o nloptr.so dummy.o nloptr.o -L/opt/vertica/R/lib -lR
installing to /opt/vertica/R/library/nloptr/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/opt/vertica/R/library/nloptr/libs/nloptr.so':
  /opt/vertica/R/library/nloptr/libs/nloptr.so: undefined symbol: nlopt_set_maxtime
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/opt/vertica/R/library/nloptr’
Error: Command failed (1)
`

It just doesnt load the shared object in any case. 
Let me know if there is something else that I may try here.

**Comment by jyypma** [comment]
Could you provide the output of

pkg-config --exists nlopt
pkg-config --libs nlopt
pkg-config --cflags nlopt
pkg-config --modversion nlopt

Thanks.

On Tue, Mar 1, 2016 at 11:01 AM, Rahul Vishwakarma <notifications@github.com

**Comment by Kaju-Bubanja** [comment]
Since this issue seems to not be fixed and I would like not to use the hack mentioned above here is my output to the requested commands:
pkg-config --exists nlopt: Nothing
pkg-config --libs nlopt: -L/usr/local/lib -lnlopt -lm
pkg-config --cflags nlopt: -I/usr/local/include
pkg-config --modversion nlopt: 2.4.2
