### ISSUE TITLE
random ERROR

### ISSUE THREAD

**Issue by FlorianSchwendinger** [astamm/nloptr#22]
Hello,

I get the following error message

```
Error: nlopt_add_inequality_mconstraint returned NLOPT_INVALID_ARGS.
Error: Test failed: 'Test HS023.'
* Not expected: res$solution not equal to solution.opt
1/2 mismatches (average diff: 2).
First 1:
 pos x y diff
   1 3 1    2.
* Not expected: all(eval_g_ineq(res$solution)$constr <= res$options$tol_constraints_ineq) isn't true.
```

kind of randomly.

I tried to come up with an minimal reproducible example based on your test `"test-hs023.R"`.
Since the error occurrence follows a Poisson distribution on my laptop

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nloptr_1.0.4    testthat_0.11.0

loaded via a namespace (and not attached):
[1] memoise_1.0.0 crayon_1.3.1  digest_0.6.9 
```

I just put your test case in a for loop.

``` r
library(testthat)
library(nloptr)

sessionInfo()

for ( i in seq_len(1000) ) {
    source("test-hs023.R")
}
```

Or alternative to show when the error occurs.

```
err <- integer(100)
for (j in 1:100) {
    print(j)
    err[j] <- tryCatch({
        for ( i in seq_len(1000) ) {
            source("test-hs023.R")
        }
    }, error=function(e) return(i))
}
hist(err)
summary(err)
sort(table(err))
```

I hope this helps and is reproducible.

Best Florian

**Comment by jyypma** [comment]
Hi Florian,

thank you for your message. Given the randomness, I'm guessing this will be
a very difficult error to solve. I can reproduce it on my system and will
try to look into this.

Best wishes,
Jelmer

**Comment by Fl0Sch** [comment]
Hi,

I found the following!
In nloptr.c line 823 you find,
```
for (i=0;i<num_constraints_ineq;i++) {
    tol_constraints_ineq[ i ] = REAL( R_tol_constraints_ineq )[ i ];
}
```
I think the issue is that, in this test case the length of `R_tol_constraints_ineq` is always 1 and `num_constraints_ineq` is 5, therefore the values `2:4` of `tol_constraints_ineq` are not properly initialized. When changing the code above to
```
Rprintf("len R_tol_constraints_ineq: %i\n", GET_LENGTH(R_tol_constraints_ineq));
Rprintf("len num_constraints_ineq: %i\n", num_constraints_ineq);      
for (i=0;i<num_constraints_ineq;i++) {
    tol_constraints_ineq[ i ] = REAL( R_tol_constraints_ineq )[ i ];
    Rprintf("    %f\n", tol_constraints_ineq[i]);
 }
```
you see that the values of `tol_constraints_ineq[2:4]` are mostly 0 sometimes some really big numbers and sometimes `-0.0000` than it fails.

Best Florian

**Comment by FlorianSchwendinger** [comment]
Hi,

I found the following!
In nloptr.c line 823 you find,

```
for (i=0;i<num_constraints_ineq;i++) {
    tol_constraints_ineq[ i ] = REAL( R_tol_constraints_ineq )[ i ];
}
```

I think the issue is that, in this test case the length of `R_tol_constraints_ineq` is always 1 and `num_constraints_ineq` is 5, therefore the values `2:4` of `tol_constraints_ineq` are not properly initialized. When changing the code above to

```
Rprintf("len R_tol_constraints_ineq: %i\n", GET_LENGTH(R_tol_constraints_ineq));
Rprintf("len num_constraints_ineq: %i\n", num_constraints_ineq);      
for (i=0;i<num_constraints_ineq;i++) {
    tol_constraints_ineq[ i ] = REAL( R_tol_constraints_ineq )[ i ];
    Rprintf("    %f\n", tol_constraints_ineq[i]);
 }
```

you see that the values of `tol_constraints_ineq[2:4]` are mostly 0 sometimes some really big numbers and sometimes `-0.0000` than it fails.

Best Florian

**Comment by Overlytic** [comment]
I am also getting the above error, also randomly distributed. Florian's suggestion sounds like a very likely cause for the error. I take it there is no easy way around it in the meantime?

I tried setting the _R_tol_constraints_ineq_ equal to a vector instead of just one number, but that didn't seem to work unfortunately.

Ended up having to use a for loop over the nloptr call until the error does not occur. But this does unfortunately make the process much more inefficient.
