### ISSUE TITLE
Hessian preconditioning in NLOPT_LD_CCSAQ

### ISSUE THREAD

**Issue by pata-eth** [astamm/nloptr#23]
Hi, in the nlopt website the author describes a way to provide a user-supplied hessian with the NLOPT_LD_CCSAQ. How we can do that in R with your package?

http://ab-initio.mit.edu/wiki/index.php/NLopt_Reference#Preconditioning_with_approximate_Hessians

Thank you

**Comment by jyypma** [comment]
This feature is not implemented in the R package.

Best wishes,
Jelmer

**Comment by aadler** [comment]
@astamm this should probably be closed based on @jyypma email.

**Comment by astamm** [comment]
Which email? It might be useful to implement it. Did @jyypma advise against that?

**Comment by eddelbuettel** [comment]
@astamm Presumably https://github.com/astamm/nloptr/issues/23#issuecomment-237933210 two comments above yours.

**Comment by aadler** [comment]
https://github.com/astamm/nloptr/issues/23#issuecomment-237933210

**Comment by jyypma** [comment]
This feature could be implemented in the R package. I've never implemented
it, because I never felt the need to use this. Also, the NLopt
documentation mentions "Currently, support for preconditioners in NLopt is
somewhat experimental, and is only used in the NLOPT_LD_CCSAQ algorithm."
https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#preconditioning-with-approximate-hessians

**Comment by astamm** [comment]
Ok. It does not seem like an impossible thing to do. The fact that it is still experimental however makes me think we should wait. @pata-eth is this something you really want to try out right now ?

**Comment by pata-eth** [comment]
Hey folks. It's been a while. I'm no longer in need of this feature and given the lack of plus ones in 7 years I'd say let's close this one. Cheers

**Comment by astamm** [comment]
Thanks for the quick reply.
