### ISSUE TITLE
Named starting parameter vector not named anymore after two iterations

### ISSUE THREAD

**Issue by PhilippBuehler** [astamm/nloptr#61]
I dont know if this is intended or not.
I like to use a named starting parameter, but the starting parameter vector is only named in the first two iteration steps. Starting with the third iteration step, the vector is not named anymore!

```
library(nloptr)

fr <- function(x){
	print(names(x))
	100 * (x[2] - x[1]^2)^2 + (1 - x[1])^2
}

Start_par <- setNames(c(0.5, 0.25, 0.5),c("Hello","World","!!!"))

S <- bobyqa(Start_par, fr, lower = c(0, 0, 0), upper = c(0.5, 0.5, 0.5))
```

Console Output:
> [1] "Hello" "World" "!!!"  
[1] "Hello" "World" "!!!"  
NULL
NULL
NULL
NULL
..

**Comment by jyypma** [comment]
Before nloptr starts iterating towards a solution, the objective function
is evaluated twice, e.g. to check that the function returns a finite value.
Since the function is called from R, the names of the parameter vector are
maintained. During the optimization, the objective function is called from
C instead of R, and names are not maintained.

You can see that the iteration starts after the second function evaluation
in the following code:

```{r}
fr <- function(x) {
  cat("function evaluated", global_niter, "times (global counter)\n")
  global_niter <<- global_niter + 1
  print(names(x))
  100 * (x[2] - x[1]^2)^2 + (1 - x[1])^2
}

opts <- list("algorithm"="NLOPT_LN_BOBYQA",
             "xtol_rel"=1.0e-8,
             "print_level" = 1,
             "maxeval" = 4)

global_niter <- 1 # Global counter to show how many times fr has been
evaluated.
S <- nloptr(Start_par, fr, lb = c(0, 0, 0), ub = c(0.5, 0.5, 0.5), opts =
opts)
```

A workaround to have access to the names of the vector, is by supplying
them to the objective function as data. See below for an example:

```{r}
fr <- function(x, x_names) {
  cat(paste0(x_names, ": " , x, collapse = ", "), "\n")
  100 * (x[2] - x[1]^2)^2 + (1 - x[1])^2
}

S <- bobyqa(Start_par, fr, lower = c(0, 0, 0), upper = c(0.5, 0.5, 0.5),
x_names = names(Start_par))

# Add names to solution.
names(S$par) <- names(Start_par)

# Show solution with names.
S
```

**Comment by eddelbuettel** [comment]
@jyypma if you remove the curlies then Github flavoured markdown will typeset as code.  The curlies are a local thing only knitr does.

```r
fr <- function(x, x_names) {
  cat(paste0(x_names, ": " , x, collapse = ", "), "\n")
  100 * (x[2] - x[1]^2)^2 + (1 - x[1])^2
}
```

That was

`````
```r
fr <- function(x, x_names) {
  cat(paste0(x_names, ": " , x, collapse = ", "), "\n")
  100 * (x[2] - x[1]^2)^2 + (1 - x[1])^2
}
```
`````

*Edit:* Forgot the `r` after the three apostrophes. Now added.

**Comment by jyypma** [comment]
Thanks, Dirk!
