### ISSUE TITLE
Slowdown when data.frame is filtered for NA values

### ISSUE THREAD

**Issue by ianarriagamackenzie** [astamm/nloptr#73]
Hello,

I am unsure how to frame this question.

We are using the 'nloptr' package, specifically the 'slsqp' function which I believe reformats the data into the 'nloptr' function, to solve a minimization equation in a large data frame (600K rows, 6 columns).

This requires that there are no NA values in the data. If we load a data set into R without NA values present, it runs very fast (~3 seconds). If we filter that exact same data set using a variety of NA filtering methods (na.rm, na.omit, which(is.na()), drop_na(), etc) and run the function again, it solves to the exact same values, however it takes approximately 10x longer (25-30s).

From a timing package (profvis) it seems that the slowdown is happening when solving for the gradient function of our objective function.  Is there anything that would cause this? This happens even when the NA filtering does not remove any rows from the data, and from what I can tell, the data.frame is exactly the same.

**Comment by jyypma** [comment]
Do you remove the NA values using a statement within the objective function?

The slsqp function uses finite differences to approximate the gradient,
which means that to calculate the gradient with respect to p parameters,
the objective function will be called p times. If there is some statement
that takes a bit of time to execute in the objective function, then it will
be called p times for one iteration of the optimizer.

In principle, if you can move calculations outside of the objective
function (because the result of the calculation does not depend on the
parameters you're optimizing over) it's almost always a good idea to do
this.

You can compare the execution time of two different objective functions to
check whether this results in the same difference in speed that you mention
below.

**Comment by ianarriagamackenzie** [comment]
Fixed, thank you!
