### ISSUE TITLE
Plotting searching space

### ISSUE THREAD

**Issue by jfjara17** [astamm/nloptr#83]
Hi, I'm using **sbplx** as a way of hyperparameter calibration for a machine learning model. 

Is it possible to get the log of the optimization path in order to plot it and visualize the behavior of the algorithm in the hyperparameter space?

**Comment by jyypma** [comment]
One solution would be to store the optimization path in a global variable from the objective function. See example below.

```
library(nloptr)

# Create global variable to store x's.
xpath <- NULL

# Fletcher and Powell's helic valley
fphv <- function(x) {
  fn <- 100*(x[3] - 10*atan2(x[2], x[1])/(2*pi))^2 +
    (sqrt(x[1]^2 + x[2]^2) - 1)^2 +x[3]^2
  
  # Store x and fn in global variable xpath.
  xpath <<- rbind(xpath, c(x, fn))
  
  # Return objective value.
  return(fn)
}

# Initial values.
x0 <- c(-1, 0, 0)

# Perform optimization.
res <- sbplx(x0, fphv) 
print(res)
head(xpath)
```

**Comment by eddelbuettel** [comment]
The other approach might be to use one of the logging packages and to log to specific 'channel'.  Could even be a file (appropriately named/timestamped) and you could then recover the values.  Leads to slight complications because of serialization to text and all that.  You could use a memory cache such as Redis too.   

(The above is very nice and compact, but we generallytell folks not to grow objects via rbind.  Even a global counter that increments and just injecting into a list one collapses afterwards back into a data.frame or alike is likely quicker.)

But the key is: _you_ own your objective function and have programmatic control in it.

**Comment by jfjara17** [comment]
Thanks for the help! (and for the quick answer)
